INSERT INTO `category` (`name`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES ('Sadnice ruža', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png','<p>Ruža </p>','<p>Kraljica cveća </p>','<p>Ruže su cvet sa najvećom simbolikom i upotrebom u istoriji čovečanstva. One predstavljaju svojevrstan simbol svake bašte, i ne postoji prostor u kom se ne mogu uklopiti. Grčka pesnikinja Safo je ružu nazvala „Kraljicom cveća“ zbog lepote pupoljka, koja je oslikana na brojnim umetničkim delima, i mirisa latica, koji se koristi u eteričnim uljima i parfemima. Najstariji pisani podaci o ružama potiču iz drevne Grčke. Afroditi, boginji ženske lepote, ljubavi i plodnosti su ruže prinošene na žrtvenik. Ruže su sađene u Vavilonskim vrtovima, Solomonovim vrtovima, Epikurovom vrtu u Atini, a ostrvo Rodos (ostrvo ruža) i Rodopi (planina ruža) su dobili ime po ovoj biljci. U Rimskom carstvu venac od ruža se koristio u svim prilikama, a seljaci su bili svedeni na proizvodnju ruža umesto hrane zarad zadovoljstva svojih vladara. Vojskovođe su kićene ružama nakon pobeda u bitkama, a cvetom ruže je kićeno pobedničko oružije. Ruže su oduvek bile predmet mnogih istraživanja. Brojnim spontanim ili veštačkim ukrštanjima izbrisale su se granice između pojedinih grupa ruža koje su ranije postojale. Procenjuje se da je do sada stvoreno oko 35 000 sorti ruža. Mali deo ovih sorti možete naći i u našoj ponudi.</p>','<p>Ruža</p>
 <p>Kraljica cveća</p>
 <p>Ruže su cvet sa najvećom simbolikom i upotrebom u istoriji čovečanstva. One predstavljaju svojevrstan simbol svake bašte, i ne postoji prostor u kom se ne mogu uklopiti. Grčka pesnikinja Safo je ružu nazvala „Kraljicom cveća“ zbog lepote pupoljka, koja je oslikana na brojnim umetničkim delima, i mirisa latica, koji se koristi u eteričnim uljima i parfemima. Najstariji pisani podaci o ružama potiču iz drevne Grčke. Afroditi, boginji ženske lepote, ljubavi i plodnosti su ruže prinošene na žrtvenik. Ruže su sađene u Vavilonskim vrtovima, Solomonovim vrtovima, Epikurovom vrtu u Atini, a ostrvo Rodos (ostrvo ruža) i Rodopi (planina ruža) su dobili ime po ovoj biljci. U Rimskom carstvu venac od ruža se koristio u svim prilikama, a seljaci su bili svedeni na proizvodnju ruža umesto hrane zarad zadovoljstva svojih vladara. Vojskovođe su kićene ružama nakon pobeda u bitkama, a cvetom ruže je kićeno pobedničko oružije. Ruže su oduvek bile predmet mnogih istraživanja. Brojnim spontanim ili veštačkim ukrštanjima izbrisale su se granice između pojedinih grupa ruža koje su ranije postojale. Procenjuje se da je do sada stvoreno oko 35 000 sorti ruža. Mali deo ovih sorti možete naći i u našoj ponudi.</p>
 ');
INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Ukrasno bilje', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');
INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Voće', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');


INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES ('Ruže', 1,'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png','<p>Ruža</p>','<p>Kraljica cveća</p>','<p>Ruže su cvet sa najvećom simbolikom i upotrebom u istoriji čovečanstva. One predstavljaju svojevrstan simbol svake bašte, i ne postoji prostor u kom se ne mogu uklopiti. Grčka pesnikinja Safo je ružu nazvala „Kraljicom cveća“ zbog lepote pupoljka, koja je oslikana na brojnim umetničkim delima, i mirisa latica, koji se koristi u eteričnim uljima i parfemima. Najstariji pisani podaci o ružama potiču iz drevne Grčke. Afroditi, boginji ženske lepote, ljubavi i plodnosti su ruže prinošene na žrtvenik. Ruže su sađene u Vavilonskim vrtovima, Solomonovim vrtovima, Epikurovom vrtu u Atini, a ostrvo Rodos (ostrvo ruža) i Rodopi (planina ruža) su dobili ime po ovoj biljci. U Rimskom carstvu venac od ruža se koristio u svim prilikama, a seljaci su bili svedeni na proizvodnju ruža umesto hrane zarad zadovoljstva svojih vladara. Vojskovođe su kićene ružama nakon pobeda u bitkama, a cvetom ruže je kićeno pobedničko oružije. Ruže su oduvek bile predmet mnogih istraživanja. Brojnim spontanim ili veštačkim ukrštanjima izbrisale su se granice između pojedinih grupa ruža koje su ranije postojale. Procenjuje se da je do sada stvoreno oko 35 000 sorti ruža. Mali deo ovih sorti možete naći i u našoj ponudi.</p>','<p>Ruža</p>
 <p>Kraljica cveća</p>
 <p>Ruže su cvet sa najvećom simbolikom i upotrebom u istoriji čovečanstva. One predstavljaju svojevrstan simbol svake bašte, i ne postoji prostor u kom se ne mogu uklopiti. Grčka pesnikinja Safo je ružu nazvala „Kraljicom cveća“ zbog lepote pupoljka, koja je oslikana na brojnim umetničkim delima, i mirisa latica, koji se koristi u eteričnim uljima i parfemima. Najstariji pisani podaci o ružama potiču iz drevne Grčke. Afroditi, boginji ženske lepote, ljubavi i plodnosti su ruže prinošene na žrtvenik. Ruže su sađene u Vavilonskim vrtovima, Solomonovim vrtovima, Epikurovom vrtu u Atini, a ostrvo Rodos (ostrvo ruža) i Rodopi (planina ruža) su dobili ime po ovoj biljci. U Rimskom carstvu venac od ruža se koristio u svim prilikama, a seljaci su bili svedeni na proizvodnju ruža umesto hrane zarad zadovoljstva svojih vladara. Vojskovođe su kićene ružama nakon pobeda u bitkama, a cvetom ruže je kićeno pobedničko oružije. Ruže su oduvek bile predmet mnogih istraživanja. Brojnim spontanim ili veštačkim ukrštanjima izbrisale su se granice između pojedinih grupa ruža koje su ranije postojale. Procenjuje se da je do sada stvoreno oko 35 000 sorti ruža. Mali deo ovih sorti možete naći i u našoj ponudi.</p>
 ');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES ('Ruze Stablašice', 1,'images/3-2021/aa4803d2f64a023cfb5bebcd76680202.png','<p>Ruže Stablašice</p>','<p>Princeze među ružama</p>','<p>Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>','<p>Ruža</p>
 <p>Kraljica cveća</p>
 <p>Ruže su cvet sa najvećom simbolikom i upotrebom u istoriji čovečanstva. One predstavljaju svojevrstan simbol svake bašte, i ne postoji prostor u kom se ne mogu uklopiti. Grčka pesnikinja Safo je ružu nazvala „Kraljicom cveća“ zbog lepote pupoljka, koja je oslikana na brojnim umetničkim delima, i mirisa latica, koji se koristi u eteričnim uljima i parfemima. Najstariji pisani podaci o ružama potiču iz drevne Grčke. Afroditi, boginji ženske lepote, ljubavi i plodnosti su ruže prinošene na žrtvenik. Ruže su sađene u Vavilonskim vrtovima, Solomonovim vrtovima, Epikurovom vrtu u Atini, a ostrvo Rodos (ostrvo ruža) i Rodopi (planina ruža) su dobili ime po ovoj biljci. U Rimskom carstvu venac od ruža se koristio u svim prilikama, a seljaci su bili svedeni na proizvodnju ruža umesto hrane zarad zadovoljstva svojih vladara. Vojskovođe su kićene ružama nakon pobeda u bitkama, a cvetom ruže je kićeno pobedničko oružije. Ruže su oduvek bile predmet mnogih istraživanja. Brojnim spontanim ili veštačkim ukrštanjima izbrisale su se granice između pojedinih grupa ruža koje su ranije postojale. Procenjuje se da je do sada stvoreno oko 35 000 sorti ruža. Mali deo ovih sorti možete naći i u našoj ponudi.</p>
 ');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Naše preporuke', 1,'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');


INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Četinari', 2,'images/3-2021/5a78205980977a33d336f886a13c707a.png');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Lišćari', 2,'images/3-2021/13a496477df9929cf96e38dcbc0a8c5.png');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Topijarne forme', 2,'images/3-2021/6289538144ab785d93cc6f37816cc0e2.png');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Ukrasne trave i perene', 2,'images/3-2021/11707358adff0c7263f6bb37282e9133.png');

INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Specijalna selekcija', 3,'images/3-2021/1fbc85ccc45fbb201b8d538db484a495.png');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Klasično voće', 3,'images/3-2021/878a3a43dbf1e62d0984db4bdaa884eb.png');
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES ('Bobičasto voće', 3,'images/3-2021/ede3e8d82c9f0cf332a82a247fb2b53d.png');

-- Ruže
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES
('Čajevke', 4, 'images/12-2020/piramidalni.jpg', '<p>Ruže Čajevke</p>', '<p>Krupni cvetovi idealni za svaki vrt ali i vazu</p>', '<p>Čajnohibridne (Tea hibridi (T.H.)) ruže karakteriše snažan porast i visoki izdanci sa krupnim cvetom na kraju svake grane. Biljke su visine do 1 m, a najčešće između 60 i 80 cm ( u zavisnosti od sorte mesta sađenja i klime). Sadnice su plemenite forme, najčešće mirisne i pogodne za rezanje, krupnih cvetova i velikog izbora boja. Mogu se saditi u svim tipovima vrtova. Sade se u grupama, vrstama, gredicama, pojedinačno ili vezano sa drugim biljkama. Rastojanje pri sadnji je 40- 45 cm ili 5-6 komada po kvadratnom metru.</p>', '<p>Ruže Čajevke</p>
 <p>Krupni cvetovi idealni za svaki vrt ali i vazu</p>
 <p>Čajnohibridne (Tea hibridi (T.H.)) ruže karakteriše snažan porast i visoki izdanci sa krupnim cvetom na kraju svake grane. Biljke su visine do 1 m, a najčešće između 60 i 80 cm ( u zavisnosti od sorte mesta sađenja i klime). Sadnice su plemenite forme, najčešće mirisne i pogodne za rezanje, krupnih cvetova i velikog izbora boja. Mogu se saditi u svim tipovima vrtova. Sade se u grupama, vrstama, gredicama, pojedinačno ili vezano sa drugim biljkama. Rastojanje pri sadnji je 40- 45 cm ili 5-6 komada po kvadratnom metru.</p>
 '),
('Mnogocvetnice', 4, 'images/12-2020/kuglaste.jpg', '<p>Mnogocvetnice | Polijante</p>', '<p>Cvetni masivni pogodni za svaki prostor</p>', '<p>Biljke uspravnog i žbunastog rasta, visokih izdanaka od 40-90 cm (u zavisnosti od sorte, mesta sađenja i klime); često sa mirisnim cvetovima, koji se formiraju u buketima. Cvetaju obilno cele sezone, pa se sađenjem u masi postižu snažni efekti. Pogodne su za sađenje: kod svih tipova kućnih vrtova, pored staza, u parkovima, pored ulica, kao cvetne žive ograde, leje i bordure. Treba težiti jednobojnim efektima i voditi računa o skladu boja i visina, za višebojne grupe. Sade se na rastojanju od 30- 40 cm ili 6-8 biljaka po metru kvadratnom.</p>', '<p>Mnogocvetnice | Polijante</p>
 <p>Cvetni masivni pogodni za svaki prostor</p>
 <p>Biljke uspravnog i žbunastog rasta, visokih izdanaka od 40-90 cm (u zavisnosti od sorte, mesta sađenja i klime); često sa mirisnim cvetovima, koji se formiraju u buketima. Cvetaju obilno cele sezone, pa se sađenjem u masi postižu snažni efekti. Pogodne su za sađenje: kod svih tipova kućnih vrtova, pored staza, u parkovima, pored ulica, kao cvetne žive ograde, leje i bordure. Treba težiti jednobojnim efektima i voditi računa o skladu boja i visina, za višebojne grupe. Sade se na rastojanju od 30- 40 cm ili 6-8 biljaka po metru kvadratnom.</p>
 '),
('Penjačice', 4, 'images/12-2020/zbunasti.jpg', '<p>Penjačice | Puzavice</p>', '<p>Prirodni cvetni zidovi za novu dimenziju svakog vrta</p>', '<p>Divnih cvetova, snažnog rasta, visine do 4 m. Cvetaju cele sezone. Pogodne su za formiranje pergola, hladnjaka, cvetnih živih ograda, maskiranje zidova i neuglednih pozadina. Biljke imaju visoke izdanke i ako želimo da ostanu uspravne, moramo tražiti oslonac; u suprotnom će padati na dole, što može izgledati privlačno ako su u vrsti. Ako im klima i mesto sađenja odgovaraju, zavosno od sorte, mogu narasti i do 4 metra. Obavezno ih skraćivati svake godine za trećinu. Sade se na rastojanju 1-1,5 metra.</p>', '<p>Penjačice | Puzavice</p>
 <p>Prirodni cvetni zidovi za novu dimenziju svakog vrta</p>
 <p>Divnih cvetova, snažnog rasta, visine do 4 m. Cvetaju cele sezone. Pogodne su za formiranje pergola, hladnjaka, cvetnih živih ograda, maskiranje zidova i neuglednih pozadina. Biljke imaju visoke izdanke i ako želimo da ostanu uspravne, moramo tražiti oslonac; u suprotnom će padati na dole, što može izgledati privlačno ako su u vrsti. Ako im klima i mesto sađenja odgovaraju, zavosno od sorte, mogu narasti i do 4 metra. Obavezno ih skraćivati svake godine za trećinu. Sade se na rastojanju 1-1,5 metra.</p>
 '),
('Grmolike', 4, 'images/12-2020/cajevke.jpg', '<p>Grmolike</p>', '<p>Žbunovite , bujne , ukrasne buketuše za prirodni izgled vrta</p>', '<p>Grmolike imaju širok spektar korišćenja. Od njih se prave cvetne žive ograde, obojene cvetne leje, čak i male šume. Po pravilu se sade pored ograde. Za pojedinačno sađenje se koristi štap kao oslonac. Opšta karakteristika im je mnogocvetnost, otpornost na bolesti i niske temperature, ali i izrazito jak rast. Biljke su uspravnog rasta ili žbunaste obično izdanaka visokih do 2 m (u zavisnosti od sorte, mesta i klime), mnogobrojnih raskošnih cvetova i divnih mirisa. Sade se na rastojanju 60-100 cm ili 1-2 sadnice po metru kvadratnom, u zavisnosti od bujnosti i sečenja izdanaka.</p>', '<p>Grmolike</p>
 <p>Žbunovite , bujne , ukrasne buketuše za prirodni izgled vrta</p>
 <p>Grmolike imaju širok spektar korišćenja. Od njih se prave cvetne žive ograde, obojene cvetne leje, čak i male šume. Po pravilu se sade pored ograde. Za pojedinačno sađenje se koristi štap kao oslonac. Opšta karakteristika im je mnogocvetnost, otpornost na bolesti i niske temperature, ali i izrazito jak rast. Biljke su uspravnog rasta ili žbunaste obično izdanaka visokih do 2 m (u zavisnosti od sorte, mesta i klime), mnogobrojnih raskošnih cvetova i divnih mirisa. Sade se na rastojanju 60-100 cm ili 1-2 sadnice po metru kvadratnom, u zavisnosti od bujnosti i sečenja izdanaka.</p>
 '),
('Minijaturne', 4, 'images/12-2020/mnogosvetnice.jpg', '<p>Minijaturne</p>', '<p>Male i otmene ruže prikladne za moderne položaje</p>', '<p>Ove male princeze među ružama pogodne su za sadnju na balkonima, u saksijama i žardinjerama, kamenjarima, u kombinaciji sa niskim četinarima, ali divno izgledaju i pored staza i kao formirane bordure. Osnovna odlika minijaturnih ruža je njihova veličina. Pored niskog rasta koji dostiže visinu do 35 cm, imaju i male listove, ali i manje cvetove od standardnih ruža. Tokom cele vegetacije bogato i neprestano se pojavljuju sitni cvetovi. Sade se na rastojanju od 25-30 cm ili 10-12 biljaka po metru kvadratnom. Ako se sade u saksije prečnik i dubina posude mora biti najmanje 30 cm.</p>', '<p>Minijaturne</p>
 <p>Male i otmene ruže prikladne za moderne položaje</p>
 <p>Ove male princeze među ružama pogodne su za sadnju na balkonima, u saksijama i žardinjerama, kamenjarima, u kombinaciji sa niskim četinarima, ali divno izgledaju i pored staza i kao formirane bordure. Osnovna odlika minijaturnih ruža je njihova veličina. Pored niskog rasta koji dostiže visinu do 35 cm, imaju i male listove, ali i manje cvetove od standardnih ruža. Tokom cele vegetacije bogato i neprestano se pojavljuju sitni cvetovi. Sade se na rastojanju od 25-30 cm ili 10-12 biljaka po metru kvadratnom. Ako se sade u saksije prečnik i dubina posude mora biti najmanje 30 cm.</p>
 '),
('Polegle', 4, 'images/12-2020/mnogosvetnice.jpg', '<p>Polegle Ruže</p>', '<p>Cvetne alternativne za monotone zelene površine</p>', '<p>Spadaju u novu grupu ruža koje su zadnjih godina veoma popularne i koje se stalno uvećavaju novim selekcijama. Imaju bujnu vegetaciju, rastu poleglo pokrivajući zemlju, praveći pravu malu šumu. Sade se po parkovima i vrtovima, kao dopuna drugim biljkama, ali i kao samostalne celine. Odlične su na padinama i kao ograde. Ne moraju se orezivati redovno, već se to može uraditi jednom u 3-4 godine. Veoma su otporne na bolesti. Zbog velike površine koju pokrivaju veoma su ekonomične. Dele se u dve grupe: I grupa: visine do 30 cm, priljubljuju se uz zemlju, ako se posade na balkon, mnoštvo cvetova će dekorativno padati na dole. Sade se na rastojanju 60- 80 cm ili 2-3 biljake po metru kvadratnom II grupa: imaju bujniji porast, u visinu od 40 – 100 cm i isto toliko u širinu. Sade se na rastojanju 40- 60 cm ili 3-6 biljaka po metru kvadratnom</p>', '<p>Polegle Ruže</p>
 <p>Cvetne alternativne za monotone zelene površine</p>
 <p>Spadaju u novu grupu ruža koje su zadnjih godina veoma popularne i koje se stalno uvećavaju novim selekcijama. Imaju bujnu vegetaciju, rastu poleglo pokrivajući zemlju, praveći pravu malu šumu. Sade se po parkovima i vrtovima, kao dopuna drugim biljkama, ali i kao samostalne celine. Odlične su na padinama i kao ograde. Ne moraju se orezivati redovno, već se to može uraditi jednom u 3-4 godine. Veoma su otporne na bolesti. Zbog velike površine koju pokrivaju veoma su ekonomične. Dele se u dve grupe: I grupa: visine do 30 cm, priljubljuju se uz zemlju, ako se posade na balkon, mnoštvo cvetova će dekorativno padati na dole. Sade se na rastojanju 60- 80 cm ili 2-3 biljake po metru kvadratnom II grupa: imaju bujniji porast, u visinu od 40 – 100 cm i isto toliko u širinu. Sade se na rastojanju 40- 60 cm ili 3-6 biljaka po metru kvadratnom</p>
 '),
('Engleske', 4, 'images/12-2020/mnogosvetnice.jpg', '<p>Engleske Ruže</p>', '<p>Najbolje osobine starinskih ruža za moderne vrtove</p>', '<p>Engleske ruže predstavljaju grupu ruža koja je uspela da iskoristi genetski potencijal starinskih ruža njihovim ukrštanjem sa savremenim selekcijama i na taj način proizvede novu gupu ruža u svetu poznatu kao New English Roses. Naziv su dobile po selekcionaru koji je uspeo da ih stvori, a potiče iz Engleske. U modernom baštovanstu glavni problem starinskih sorti je bilo njihovo cvetanje koje se dešava samo jednom u toku sezone  u proleće i nakon toga biljka više ne proizvodi cvet do sledeće godine. Stoga je ideja prilikom stvaranja ove grupe ruža bila da  nastanu sorte koje će cvetati tokom cele godine, imati izgled starinskih cvetova koji su veoma krupni i mirisni sa izrazito velikim brojem latica. Danas je poznat veliki broj sorti koje pripadaju Engleskim ružama, koji se iz godine u godinu uvećava.</p>', '<p>Engleske Ruže</p>
 <p>Najbolje osobine starinskih ruža za moderne vrtove</p>
 <p>Engleske ruže predstavljaju grupu ruža koja je uspela da iskoristi genetski potencijal starinskih ruža njihovim ukrštanjem sa savremenim selekcijama i na taj način proizvede novu gupu ruža u svetu poznatu kao New English Roses. Naziv su dobile po selekcionaru koji je uspeo da ih stvori, a potiče iz Engleske. U modernom baštovanstu glavni problem starinskih sorti je bilo njihovo cvetanje koje se dešava samo jednom u toku sezone  u proleće i nakon toga biljka više ne proizvodi cvet do sledeće godine. Stoga je ideja prilikom stvaranja ove grupe ruža bila da  nastanu sorte koje će cvetati tokom cele godine, imati izgled starinskih cvetova koji su veoma krupni i mirisni sa izrazito velikim brojem latica. Danas je poznat veliki broj sorti koje pripadaju Engleskim ružama, koji se iz godine u godinu uvećava.</p>
 ');


-- Ruže Stablašice
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES
('Kuglaste', 5, 'images/12-2020/piramidalni.jpg', '<p>Ruze Stablašice</p>', '<p>Princeze među ružama</p>', '<p>Formiraju kuglastu (loptastu) krošnju, tj. grane ovih ruža rastu uspravno praveći kuglastu formu. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>', '<p>Ruze Stablašice</p>
 <p>Princeze među ružama</p>
 <p>Formiraju kuglastu (loptastu) krošnju, tj. grane ovih ruža rastu uspravno praveći kuglastu formu. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>
 '),
('Padajuće', 5, 'images/12-2020/kuglaste.jpg', '<p>Ruze Stablašice</p>', '<p>Princeze među ružama</p>', '<p>Grane ovih ruža povijaju se prema zemlji i na taj način biljka dobija žalosnu formu. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>', '<p>Ruze Stablašice</p>
 <p>Princeze među ružama</p>
 <p>Grane ovih ruža povijaju se prema zemlji i na taj način biljka dobija žalosnu formu. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>
 '),
('Mini', 5, 'images/12-2020/zbunasti.jpg', '<p>Ruze Stablašice</p>', '<p>Princeze među ružama</p>', '<p>Krošnja ove grupe ruža je manja od standardnih, sa sitnijim cvetovima i listovima. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>', '<p>Ruze Stablašice</p>
 <p>Princeze među ružama</p>
 <p>Krošnja ove grupe ruža je manja od standardnih, sa sitnijim cvetovima i listovima. Stablašice su princeze među ružama. Svojom specifičnošću, dekorativnošću i izuzetnom lepotom dominiraju svakim prostorom u kom se nađu. Mogu se saditi pojedinačno kao samostalni soliteri, u vidu predivnih drvoreda, u kombinaciji sa poleglim četinarima ili niskim šimširom, patuljastim ružama ili perenama pri čemu stablašica zauzima centralnu poziciju. Veoma su pogodne za sadnju u vrtovima ali i u urbanim prostorima, u saksijama, na terasama, ispred reprezentativnih ulaza, lokala.</p>
 ');


-- Naše preporuke
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES
('Kordes selekcija', 6, 'images/12-2020/piramidalni.jpg', '<p>Kordes Selekcija</p>', '<p>Zagarantovan kvalitet</p>', '<p>Kordes selekcija - predstavlja garanciju kvaliteta neke sorte koju izdaje oficijalni partner i proizvođač Kordes. Proizvodnja ruža sa ovom oznakom je kontrolisana od strane stručnjaka iz Nemačke, a samim tim je garantovana autentičnost sorte kao i kvalitet sadnica prilikom isporuke. Ruže sa ovom oznakom su licencirane. Veliko nam je zadovoljstvo da Vas obavestimo da je od Januara 2017. godine Rasadnik Topalović postao oficijalni proizvođač i distributer rasadnika W. Kordes’ Söhne iz Nemačke za Srbiju, zemlje bivše Jugoslavije i Rusiju. Kordes RoseS je porodična firma osnovana 1887. godine na severu Nemačke i jedan je od najvećih i najuticajnijih rasadnika i uzgajivača ruža u svetu, koja je tokom godina stvorila neke od najprepoznatljivijih i najboljih sorti ruža u istoriji. Ovim partnerstvom Rasadnik Topalović se trudi da tržištu ponudi najkvalitetnije i najnovije sorte, što do sada i nije bilo tako lako. Rezultate ove saradnje možete videti već ove sezone u vidu kontrole kvaliteta sorti koje je stvorio Kordes, dok smo za sledeću godinu obezbedili preko 20 novih vrsta koje su svojom otpornošću i kvalitetom našle svoje mesto u brojnim vrtovima u svetu.</p>', '<p>Kordes Selekcija</p>
 <p>Zagarantovan kvalitet</p>
 <p>Kordes selekcija - predstavlja garanciju kvaliteta neke sorte koju izdaje oficijalni partner i proizvođač Kordes. Proizvodnja ruža sa ovom oznakom je kontrolisana od strane stručnjaka iz Nemačke, a samim tim je garantovana autentičnost sorte kao i kvalitet sadnica prilikom isporuke. Ruže sa ovom oznakom su licencirane. Veliko nam je zadovoljstvo da Vas obavestimo da je od Januara 2017. godine Rasadnik Topalović postao oficijalni proizvođač i distributer rasadnika W. Kordes’ Söhne iz Nemačke za Srbiju, zemlje bivše Jugoslavije i Rusiju. Kordes RoseS je porodična firma osnovana 1887. godine na severu Nemačke i jedan je od najvećih i najuticajnijih rasadnika i uzgajivača ruža u svetu, koja je tokom godina stvorila neke od najprepoznatljivijih i najboljih sorti ruža u istoriji. Ovim partnerstvom Rasadnik Topalović se trudi da tržištu ponudi najkvalitetnije i najnovije sorte, što do sada i nije bilo tako lako. Rezultate ove saradnje možete videti već ove sezone u vidu kontrole kvaliteta sorti koje je stvorio Kordes, dok smo za sledeću godinu obezbedili preko 20 novih vrsta koje su svojom otpornošću i kvalitetom našle svoje mesto u brojnim vrtovima u svetu.</p>
 '),
('Adr selekcija', 6, 'images/12-2020/kuglaste.jpg', '<p>ADR selekcija</p>', '<p>Ruže sa ADR ROSE nagradom</p>', '<p>Ovo priznanje se dodeljuje ružama sa kvalitetom iznad standarda i važi za jedno od najizazovnijih takmičenja u svetu ružarstva. Tokom perioda od tri godine testiraju se i analiziraju ruže po sledećim kriterijumima: otpornost na bolesti, jačina sorte, energija rasta, forma cveta, dužina cvetanja, boja cveta od formiranja pupoljaka do precvetavanja, kao i generalni utisak same biljke. U testiranju nije dozvoljena upotreba pesticida zbog što realnije ocene prirodne lepote i otpornosti sorte. Kako se standardi svake godine povećavaju, tako i ova nagrada nije trajna, samim tim može biti povučena kada sorta više ne ispunjava kriterijume. Do sada je testirano preko 2000 sorti ruža, ali se samo mali broj sorti može pohvaliti ADR nagradom i možete biti sigurni da je svaka sorta iz ove selekcije pravi izbor za Vaš vrt.</p>', '<p>ADR selekcija</p>
 <p>Ruže sa ADR ROSE nagradom</p>
 <p>Ovo priznanje se dodeljuje ružama sa kvalitetom iznad standarda i važi za jedno od najizazovnijih takmičenja u svetu ružarstva. Tokom perioda od tri godine testiraju se i analiziraju ruže po sledećim kriterijumima: otpornost na bolesti, jačina sorte, energija rasta, forma cveta, dužina cvetanja, boja cveta od formiranja pupoljaka do precvetavanja, kao i generalni utisak same biljke. U testiranju nije dozvoljena upotreba pesticida zbog što realnije ocene prirodne lepote i otpornosti sorte. Kako se standardi svake godine povećavaju, tako i ova nagrada nije trajna, samim tim može biti povučena kada sorta više ne ispunjava kriterijume. Do sada je testirano preko 2000 sorti ruža, ali se samo mali broj sorti može pohvaliti ADR nagradom i možete biti sigurni da je svaka sorta iz ove selekcije pravi izbor za Vaš vrt.</p>
 '),
('Kolekcija jestivih ruža', 6, 'images/12-2020/zbunasti.jpg', '<p>Kolekcija jestivih ruža</p>', '<p>Pogled na ruže iz potpuno nove perspektive</p>', '<p>Vreme ja pogledate svoje ruže iz potpuno nove perspektive! S obzirom da mnogi ljudi gaje ruže isključivo zbog izuzetne lepote njihovih cvetova, lako je smetnuti s uma da su ruže zapravo jestive. Štaviše, ruže se preko hiljadu godina gaje zbog svojih hranljivih, lekovitih i kozmetičkih svojstava. Plodovi ruža se koriste za džemove i marmelade, dok se ružine latice koriste za čajeve, salate, različite vrste slatkiša, sosove, začine i sirće. Činjenica da se ova ukrasna biljka koristi za ishranu uopšte nije iznenađujuća. Porodica ruža (Rosaceae) pored ruža uključuje i neke od ekonomski najznačajnijih voćnih vrsta kao što su jabuke, kruške, dunje, kajsije, šljive, trešnje, breskve, maline, jagode i bademe. Iz toga je lako zaključiti kako je najpopularnija ukrasna biljka našla svoj put do vaše kuhinje. U stvari, hemijske analize su pokazale da neke sorte ruža imaju veću nutritivnu vrednost od nekih vrsta voća i povrća. Imaju pregršt supstanci korisnih po ljudsko zdravlje, poput vitamina C, antioksidanata, šećera, lipida, proteina, tanina, pektina, aminokiselina i eteričnih ulja. Kada smo započeli nas istraživački i oplemenjivački program za jestive ruže, otkrili smo da, kao i kod ostalih voćnih vrsta, postoje sorte koje su ukusnije od drugih. Pre nego što smo sproveli panel za punoću ukusa, svi naši kandidati su prošli hemijske analize kako bi se odredio tačan sastav hranjivih materija što nam je kasnije umnogome pomoglo da povežemo određena jedinjenja sa aromom ružinih latica. To je dovelo do stvaranja ruža različitih ukusa i tekstura – od svilenkasto-slatkog do arome osvežavajućeg citrusa. Sledeći korak je bio stvaranje percepcije o jestivim ružama, zadatak u kojem su nam pomogli profesionalni kuvari iz srednjih i vrhunskih restorana. Ovde se više od 100 odabranih sorti sužava na manje od desetak – dokazujući da su samo izuzetne ruže dovoljno dobre da se zovu PGR jestive ruže.</p>', '<p>Kolekcija jestivih ruža</p>
 <p>Pogled na ruže iz potpuno nove perspektive</p>
 <p>Vreme ja pogledate svoje ruže iz potpuno nove perspektive! S obzirom da mnogi ljudi gaje ruže isključivo zbog izuzetne lepote njihovih cvetova, lako je smetnuti s uma da su ruže zapravo jestive. Štaviše, ruže se preko hiljadu godina gaje zbog svojih hranljivih, lekovitih i kozmetičkih svojstava. Plodovi ruža se koriste za džemove i marmelade, dok se ružine latice koriste za čajeve, salate, različite vrste slatkiša, sosove, začine i sirće. Činjenica da se ova ukrasna biljka koristi za ishranu uopšte nije iznenađujuća. Porodica ruža (Rosaceae) pored ruža uključuje i neke od ekonomski najznačajnijih voćnih vrsta kao što su jabuke, kruške, dunje, kajsije, šljive, trešnje, breskve, maline, jagode i bademe. Iz toga je lako zaključiti kako je najpopularnija ukrasna biljka našla svoj put do vaše kuhinje. U stvari, hemijske analize su pokazale da neke sorte ruža imaju veću nutritivnu vrednost od nekih vrsta voća i povrća. Imaju pregršt supstanci korisnih po ljudsko zdravlje, poput vitamina C, antioksidanata, šećera, lipida, proteina, tanina, pektina, aminokiselina i eteričnih ulja. Kada smo započeli nas istraživački i oplemenjivački program za jestive ruže, otkrili smo da, kao i kod ostalih voćnih vrsta, postoje sorte koje su ukusnije od drugih. Pre nego što smo sproveli panel za punoću ukusa, svi naši kandidati su prošli hemijske analize kako bi se odredio tačan sastav hranjivih materija što nam je kasnije umnogome pomoglo da povežemo određena jedinjenja sa aromom ružinih latica. To je dovelo do stvaranja ruža različitih ukusa i tekstura – od svilenkasto-slatkog do arome osvežavajućeg citrusa. Sledeći korak je bio stvaranje percepcije o jestivim ružama, zadatak u kojem su nam pomogli profesionalni kuvari iz srednjih i vrhunskih restorana. Ovde se više od 100 odabranih sorti sužava na manje od desetak – dokazujući da su samo izuzetne ruže dovoljno dobre da se zovu PGR jestive ruže.</p>
 ');



-- Cetinari
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Piramidalni', 7, 'images/12-2020/piramidalni.jpg'),
('Kuglasti', 7, 'images/12-2020/kuglaste.jpg'),
('Polegli', 7, 'images/12-2020/zbunasti.jpg'),
('Žbunasti', 7, 'images/12-2020/zbunasti.jpg');

-- Lišćari
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`, `title`, `subtitle`, `content_text`, `description`) VALUES
('Ukrasno žbunje', 8, 'images/3-2021/ede3e8d82c9f0cf332a82a247fb2b53d.png', null, null, null, null),
('Japanski javori', 8, 'images/3-2021/a6275f98e57476d3d12885de9e4b9b14.png', null, null, null, null),
('Rododendroni', 8, 'images/3-2021/ab8622221a0d0180f1e25f95c1d6fc94.png','<p>Rododendron</p>', '<p>Lepi listovi i bujno cvetanjje</p>', '<p>Rododendroni su fantastične biljke koje će oko svakog posmatrača oduševiti svojim spektakularnim cvetanjem i lepim listom. Zimzeleni žbunovi mogu biti različitih dimenzija, ali ih sve karakterišu lepo eliptično lišće, i grupisani cvetovi koji mogu dostići veličinu od 20 cm. Uz nekoliko izuzetaka uglavnom cvetaju u Maju ili Junu. Upotreba Rododendrona je gotovo neograničena: od sadnje u senci ispod drveća za dobijanje živopisnog pejzaža, preko korišćenja u bordurama i ogradama pa sve do gajenja u saksijskim uslovima na terasama. Preferiraju manje osunčana mesta, dobro drenirano i kiselo zemljište.</p>', '<p>Rododendron</p>
 <p>Lepi listovi i bujno cvetanjje</p>
 <p>Rododendroni su fantastične biljke koje će oko svakog posmatrača oduševiti svojim spektakularnim cvetanjem i lepim listom. Zimzeleni žbunovi mogu biti različitih dimenzija, ali ih sve karakterišu lepo eliptično lišće, i grupisani cvetovi koji mogu dostići veličinu od 20 cm. Uz nekoliko izuzetaka uglavnom cvetaju u Maju ili Junu. Upotreba Rododendrona je gotovo neograničena: od sadnje u senci ispod drveća za dobijanje živopisnog pejzaža, preko korišćenja u bordurama i ogradama pa sve do gajenja u saksijskim uslovima na terasama. Preferiraju manje osunčana mesta, dobro drenirano i kiselo zemljište.</p>
 '),
('Hortenzije', 8, 'images/3-2021/b2571f6dc8bcc05b051e98decaea9a83.png','<p>Hortenzije</p>', '<p>Listopadno žbunje</p>', '<p>Listopadno žbunje. Cvasti su joj krupnei loptaste. Dobro podnosi hladne uslove sredine. Zahteva vlažna i dobro drenirana zemljišta u polusenci i svakodnevno zalivanje. Odgovaraju joj mesta koja su pre podne osunčana, a posle podne u senci. Pogodna je za sadnju u žardinjerama i saksijama, ali se može gajiti i kao sobna biljka.</p>', '<p>Hortenzije</p>
 <p>Listopadno žbunje</p>
 <p>Listopadno žbunje. Cvasti su joj krupnei loptaste. Dobro podnosi hladne uslove sredine. Zahteva vlažna i dobro drenirana zemljišta u polusenci i svakodnevno zalivanje. Odgovaraju joj mesta koja su pre podne osunčana, a posle podne u senci. Pogodna je za sadnju u žardinjerama i saksijama, ali se može gajiti i kao sobna biljka.</p>
 '),
('Klematisi', 8, 'images/3-2021/13f739a25c566c9f35e610677722ea32.png','<p>Klematisi</p>', '<p>Popularne baštanske biljke</p>', '<p>Klematisi spadaju među najlepše puzavice i predstavljaju jednu od najpopularnijih baštenskih biljaka. Ova svestrana biljka može da se uzgaja uz zidove, pergole, ramove, u kontejnerima, ili jednostavno da se penje uz drveće i žbunje I na taj način potpuno daju drugačiji izgled vrtu. Iako važi mišljenje da su komplinkovani za uzgajanje, klematis predstavlja biljku koja će sa jako malo truda napraviti čuda u Vašem vrtu.</p>', '<p>Klematisi</p>
 <p>Popularne baštanske biljke</p>
 <p>Klematisi spadaju među najlepše puzavice i predstavljaju jednu od najpopularnijih baštenskih biljaka. Ova svestrana biljka može da se uzgaja uz zidove, pergole, ramove, u kontejnerima, ili jednostavno da se penje uz drveće i žbunje I na taj način potpuno daju drugačiji izgled vrtu. Iako važi mišljenje da su komplinkovani za uzgajanje, klematis predstavlja biljku koja će sa jako malo truda napraviti čuda u Vašem vrtu.</p>
 '),
('Magnolije', 8, 'images/3-2021/5836331ade3ed6cfd459d932c5367357.png', null, null, null, null),
('Puzavice', 8, 'images/3-2021/4aabd8cd8517bb81ebac7bd77e606bcc.png', null, null, null, null),
('Drvenasti Božuri', 8, 'images/12-2020/zbunasti.jpg','<p>Drvenasti Božuri</p>', '<p>Poreklo iz Kine</p>', '<p>Malo je biljaka koje se mogu meriti sa lepotom drvenastog božura u trenutku cvetanja. Drvenasti božuri potiču iz Kine gde se uzgajaju već vekovima i smatraju se za jedan od nacionalnih cvetova ove države. Pored svoje dekorativne vrednosti puno se koristi i u tradicionalnoj Kineskoj medicini. Za razliku od običnog božura ova grupa ima drvenaste grane koje ne venu tokom zimskog perioda. U proleće iz velikih pupoljaka izbijaju krupni cvetovi. Odrasli primerci mogu imati stotine cvetova do 25 cm veličine. Drvenasti božur je veoma lak za održavanje. Ne zahteva orezivanje i dovoljno je skinuti samo precvetale pupoljke ukoliko to želite. Najbolje raste na osunčanim ili polusenovitim mestima. Potrebno mu je bogato humusno, dobro drenirano ali vlažno zemljište. Cvetovi su odlični i kao rezani cvet. Podnosi temperature do -29 ° C.</p>', '<p>Drvenasti Božuri</p>
 <p>Poreklo iz Kine</p>
 <p>Malo je biljaka koje se mogu meriti sa lepotom drvenastog božura u trenutku cvetanja. Drvenasti božuri potiču iz Kine gde se uzgajaju već vekovima i smatraju se za jedan od nacionalnih cvetova ove države. Pored svoje dekorativne vrednosti puno se koristi i u tradicionalnoj Kineskoj medicini. Za razliku od običnog božura ova grupa ima drvenaste grane koje ne venu tokom zimskog perioda. U proleće iz velikih pupoljaka izbijaju krupni cvetovi. Odrasli primerci mogu imati stotine cvetova do 25 cm veličine. Drvenasti božur je veoma lak za održavanje. Ne zahteva orezivanje i dovoljno je skinuti samo precvetale pupoljke ukoliko to želite. Najbolje raste na osunčanim ili polusenovitim mestima. Potrebno mu je bogato humusno, dobro drenirano ali vlažno zemljište. Cvetovi su odlični i kao rezani cvet. Podnosi temperature do -29 ° C.</p>
 ');


-- Topijarne forme
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Kalem na štapu', 9, 'images/3-2021/84b9109ac0a906052a0fce12b7b152d8.png'),
('Spirale', 9, 'images/3-2021/844f19305240879851f22637c99c49ca.png'),
('Bonsai', 9, 'images/3-2021/c74078d0c99d66198336f250ca703086.png'),
('Ostali Topijarni oblici', 9, 'images/3-2021/d2740e7bfc93dbdc78ef0f0d592fcdc.png');


-- Ukrasne trave i perene
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Bambusi', 10, 'images/3-2021/91c54626f75c840468270375658202ce.png'),
('Ukrasne trave', 10, 'images/3-2021/11707358adff0c7263f6bb37282e9133.png'),
('Perene', 10, 'images/3-2021/11707358adff0c7263f6bb37282e9133.png');



-- Specijalna selekcija
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Starinske sorte voća', 11, 'images/3-2021/3ddfa32b66b6ff854b02cde25ab4dd25.png'),
('Stubasto voće', 11, 'images/3-2021/3ddfa32b66b6ff854b02cde25ab4dd25.png'),
('Citrusi', 11, 'images/3-2021/2eb5e9f890aa4a16be6d7450d8860bd.png'),
('Neobično voće', 11, 'images/3-2021/61ed5d9f52500c5f6f0587ab66fc21bf.png'),
('Patuljasto voće', 11, 'images/3-2021/61ed5d9f52500c5f6f0587ab66fc21bf.png');


-- Klasično voće
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Jabuke', 12, 'images/3-2021/c93284f301b6c0b99d458eb24e913e43.png'),
('Kruške', 12, 'images/3-2021/3db65902a34e0236b830f06186d6492b.png'),
('Trešnje i Višnje', 12, 'images/3-2021/413d7693c236096dd6628dfe0570afaa.png'),
('Breskve i Kajsije', 12, 'images/3-2021/863392cd413fde2e573ad01d40263796.png'),
('Šljive', 12, 'images/3-2021/af6e2506c58661c542dace894be98c13.png'),
('Orah i lešnik', 12, 'images/3-2021/8edbe4e9bb911e97ae1c7228af4ed1e1.png'),
('Dunja i Džanarika', 12, 'images/3-2021/7b776f3658639e69b5c95c0085786c59.png');


-- Bobičasto voće
INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Vinova loza', 13, 'images/3-2021/4d583d3950236839c79d21daf95bd02d.png'),
('Jagode', 13, 'images/3-2021/7da7a645e12076449f6710b1e25516a7.png'),
('Ogrozd', 13, 'images/3-2021/f9b3b9c293a2a488a3d03b511a709fda.png'),
('Ribizla', 13, 'images/3-2021/75764f2187832443984ded978b139c8.png'),
('Borovnica i brusnica', 13, 'images/3-2021/d38b50cd1d320536b7020bc61d0c7943.png'),
('Aronija i Godži', 13, 'images/3-2021/e774ffbd7dbd090d2521c7798863bd5e.png'),
('Kupina i Malina', 13, 'images/3-2021/9ba1061713fc8ceac5033ff2e89fd0f6.png');


INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Najnovije sorte', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');
INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Mediteransko voće', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');

INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Ostalo', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');

INSERT INTO `category` (`name`, `parent_category_id`, `primary_image_url`) VALUES
('Seme trave', 67, 'images/3-2021/844f19305240879851f22637c99c49ca.png'),
('Dekorativni malč', 67, 'images/3-2021/84b9109ac0a906052a0fce12b7b152d8.png'),
('Đubriva', 67, 'images/3-2021/c74078d0c99d66198336f250ca703086.png'),
('Kamen oblutak', 67, 'images/3-2021/d2740e7bfc93dbdc78ef0f0d592fcdc.png');


INSERT INTO `category` (`name`, `primary_image_url`) VALUES ('Voćne sadnice', 'images/3-2021/1d32f8c3217a3da4788aa18871f77983.png');


