INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Visina rasta','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Širina rasta','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Brzina rasta','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Otpornost na bolesti','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Boja cveta','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Boja','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Vreme cvetanja','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Tip lista','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Tip ruže','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Boja lista','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Boja Ploda','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Vreme ploda','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Jačina mirisa','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Miris','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Broj latica','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Veličina cveta','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Oreginalni naziv','0','1');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Domaći naziv','0','1');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Ruski naziv','0','1');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Selekcionar','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Godina stvaranja','0','1');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Osunčanost terena','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Upotreba','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Dekorativnost','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('P15','1','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Domaći naziv-Karakteristike','0','1');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Vreme cvetanja-Dekor','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Oblik krošnje','0','0');
INSERT INTO `attribute` (`name`,`participates_in_variation`,`entered_manually`) VALUES ('Primena smeše','0','0');